### ISSUE TITLE
Accept Emcee role

### ISSUE THREAD

**Issue by MaltysFalcon** [tomgigler/GiggleMe#210]
Have a way to have the people who are given the Emcee role to agree to a doc and that triggers them getting the role

**Comment by tomgigler** [comment]
@JustinANelson FYI

The idea here is that @MaltysFalcon would have a bot command he could use to assign the Emcee role.  The bot would DM some boilerplate text to the recipient who would need to accept the terms and then the bot would assign the role

**Comment by tomgigler** [comment]
Maybe like:

`~giggle assign <role> <member> <template>`

Or even better, take the time to add slash commands so it's super easy

**Comment by tomgigler** [comment]
Oh, and then I have to handle the case where `<member>` doesn't accept the DM from the bot

**Comment by JustinANelson** [comment]
I've implemented roles via slash commands and the ability to create a button via slash command that can auto-assign roles when clicked as well via my bot. Since this isn't critical - I might self host the bot - I can add this to ACD Modbot if it makes more sense. It's even better now with fine tuned role based slash command permissions.

**Comment by JustinANelson** [comment]
Afaik slash commands aren't an option with GiggleMe

**Comment by tomgigler** [comment]
> Afaik slash commands aren't an option with GiggleMe

Not yet (or possibly ever)

**Comment by tomgigler** [comment]
I think we concluded that GiggleMe is probably not the right place to implement this
